import './globals.css'
import type { Metadata } from 'next'
import { Vazirmatn } from 'next/font/google'

const vazir = Vazirmatn({ subsets: ['latin', 'arabic'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className={vazir.className}>{children}</body>
    </html>
  )
}
